"""Canonical Version 6.0 asset catalogue.

Names and counts are frozen from the Step #1–Step #6 architecture. Additions must
use the next identifier and preserve historical aliases through the registry.
"""

FAMILIES = {
    "DNA": [
        "Truth-First DNA", "Preservation-First DNA", "Infinite Compounding DNA",
        "Parallel Intelligence DNA", "Autonomous Completion DNA", "Decomposition DNA",
        "Adversarial Resilience DNA", "Evidence Traceability DNA",
        "Contradiction Resolution DNA", "Finality Proof DNA", "Assetization DNA",
        "Governance DNA", "Memory and Lineage DNA", "Proportionate Complexity DNA",
        "Stewardship DNA", "Human Sovereignty DNA", "Anti-Decay DNA",
        "Universal Transfer DNA", "Epistemic Humility DNA", "Calibration DNA",
        "Causal Intelligence DNA", "Experimental Discipline DNA",
        "Economic Rationality DNA", "Incentive Alignment DNA", "Observability DNA",
        "Resilience DNA", "Security and Privacy DNA", "Interoperability DNA",
        "Adoption DNA", "Portfolio Intelligence DNA", "Semantic Integrity DNA",
        "Requirements Traceability DNA", "Data Stewardship DNA", "Model-Risk DNA",
        "Genuine Independence DNA", "Identity and Accountability DNA",
        "Third-Party Sovereignty DNA", "Financial Stewardship DNA", "Reliability DNA",
        "Incident Learning DNA", "Accessibility and Context DNA", "Documentation DNA",
        "Benefits Realization DNA", "Decommissionability DNA",
        "Unknown-Unknown Vigilance DNA",
    ],
    "OS": [
        "Sovereign Intent Interpretation OS™", "Mission Decomposition and Workgraph OS™",
        "Parallel Agent Orchestration OS™", "Agent Charter and Boundary OS™",
        "Evidence Acquisition and Source Sovereignty OS™",
        "Multi-Path Research Intelligence OS™",
        "Contradiction and Consensus Resolution OS™",
        "Adversarial Red-Team and Failure Intelligence OS™",
        "Risk, Ethics, Compliance and Stewardship OS™",
        "Synthesis and Decision Intelligence OS™", "Finality Proof and Release OS™",
        "Learning Extraction and Root-Cause OS™",
        "Codification and Intellectual Property OS™",
        "Memory, Retrieval and Golden Record OS™",
        "Scale, Automation and Distribution OS™",
        "Decay Detection and System Renewal OS™", "Sovereign Portfolio Command OS™",
        "Resource Economics and Allocation OS™",
        "Uncertainty and Confidence Calibration OS™", "Causal Intelligence OS™",
        "Experimentation and Validation Factory OS™", "Observability and Telemetry OS™",
        "Business Continuity and Resilience OS™", "Release, Rollback and Recovery OS™",
        "Security, Privacy and Trust OS™", "Model Diversity and Ensemble Intelligence OS™",
        "Interoperability and Tool-Abstraction OS™",
        "Decision Rights and Deadlock Resolution OS™",
        "Temporal Horizon and Scenario Intelligence OS™",
        "Stakeholder Ecosystem Intelligence OS™", "Human Factors and Adoption OS™",
        "Knowledge Hygiene and Purposeful Forgetting OS™",
        "Independent Audit and Reproducibility OS™",
        "Commercial Defensibility and Value Capture OS™", "Exhaustiveness Assurance OS™",
        "Unknown-Unknown Discovery OS™", "Semantic Integrity and Ontology OS™",
        "Requirements Engineering and Traceability OS™",
        "Data Governance and Master Data OS™", "Model-Risk and AI Assurance OS™",
        "Common-Mode Failure Detection OS™",
        "Identity, Authority and Non-Repudiation OS™",
        "Third-Party and Supply-Chain Governance OS™",
        "Financial Control and Capital Stewardship OS™",
        "Jurisdiction, Tax, Accounting and Insurance OS™",
        "Product and Service Lifecycle OS™", "Programme and Dependency Command OS™",
        "Service Reliability and Capacity OS™", "Incident, Problem and Crisis Command OS™",
        "Change, Configuration and Architecture Control OS™",
        "Records, Documentation and Legal Hold OS™",
        "Integrity, Fraud and Protected Disclosure OS™",
        "Accessibility, Localization and Cultural Intelligence OS™",
        "Sustainability and Externality Intelligence OS™",
        "Decommissioning, Disposal and Residual-Risk OS™", "Sovereign Meta-Governor OS™",
        "Sovereign Calibre Assurance and Certification OS™",
        "Asset Registry, Dependency and Interface OS™",
        "Canonical Estate Coherence and Reconciliation OS™",
        "Implementation Command and Activation OS™",
        "Simulation, Regression and Verification Harness OS™",
        "Competency, Training and Operator Certification OS™",
        "Legal, Intellectual Property and Brand Clearance OS™",
        "Estate Economics, Funding and Capacity OS™",
        "Operating Rhythm and Governance Calendar OS™",
        "Pilot Portfolio and Evidence Accumulation OS™",
    ],
    "Engine": [
        "Infinite Compounding Engine™", "Parallel Intelligence Multiplication Engine™",
        "Additive Preservation Engine™", "Autonomous Mission Completion Engine™",
        "Truth and Evidence Calibration Engine™", "Contradiction Mining Engine™",
        "Failure-to-Asset Conversion Engine™", "Knowledge-to-IP Engine™",
        "Recursive Quality Elevation Engine™", "Negative-Space Intelligence Engine™",
        "Loop Immunity Engine™", "Legacy and Succession Transfer Engine™",
        "Confidence Calibration Engine™", "Causal Discovery and Attribution Engine™",
        "Experiment Factory Engine™", "Opportunity-Cost Intelligence Engine™",
        "Adaptive Resource Allocation Engine™", "Resilience and Recovery Engine™",
        "Controlled Rollback Engine™", "Trust and Integrity Protection Engine™",
        "Adoption Acceleration Engine™", "Cross-Mission Transfer Engine™",
        "Exhaustiveness Mapping Engine™", "Unknown-Unknown Discovery Engine™",
        "Semantic Consistency Engine™", "Requirements Traceability Engine™",
        "Data Quality and Lineage Engine™", "Model-Risk Boundary Engine™",
        "Common-Mode Failure Engine™", "Third-Party Sovereignty Engine™",
        "Financial Integrity Engine™", "Reliability and Incident Learning Engine™",
        "Benefits Realization Engine™", "Responsible Decommissioning Engine™",
        "Calibre Gap-Closure Engine™", "Proof-of-Operation Engine™",
        "Estate Coherence and Deduplication Engine™", "Implementation Readiness Engine™",
        "Cross-Asset Regression Assurance Engine™",
        "Evidence Accumulation and Proof Progression Engine™",
    ],
    "Framework": [
        "I.D.E.A.L. Mission Framework™", "P.A.R.A.L.L.E.L. Agent Framework™",
        "V.E.R.I.F.Y. Framework™", "C.O.M.P.O.U.N.D. Framework™",
        "A.D.D.I.T.I.V.E. Preservation Framework™", "M.U.L.T.I.P.L.Y. Leverage Framework™",
        "R.E.D. T.E.A.M. Framework™", "F.I.N.A.L.I.T.Y. Framework™",
        "A.S.S.E.T. Framework™", "R.E.N.E.W. Framework™",
        "O.R.B.I.T. Portfolio Framework™", "C.A.L.I.B.R.A.T.E. Framework™",
        "C.A.U.S.E. Framework™", "E.X.P.E.R.I.M.E.N.T. Framework™",
        "R.E.S.I.L.I.E.N.C.E. Framework™", "T.R.U.S.T. Framework™",
        "A.D.O.P.T. Framework™", "P.R.O.V.E.N. Framework™",
        "S.C.O.P.E. Exhaustiveness Framework™", "U.N.K.N.O.W.N. Discovery Framework™",
        "S.E.M.A.N.T.I.C. Framework™", "D.A.T.A. Framework™",
        "M.O.D.E.L. Assurance Framework™", "S.U.P.P.L.Y. Dependency Framework™",
        "C.O.N.T.R.O.L. Financial Framework™", "I.N.C.I.D.E.N.T. Framework™",
        "B.E.N.E.F.I.T. Realization Framework™", "E.X.I.T. Decommissioning Framework™",
        "C.A.L.I.B.R.E. Framework™", "C.E.R.T.I.F.Y. Framework™",
        "C.A.N.O.N. Framework™", "A.C.T.I.V.A.T.E. Framework™",
        "R.E.G.R.E.S.S. Framework™", "E.V.I.D.E.N.C.E. Framework™",
    ],
    "SOP": [
        "Objective Intake", "Mission Decomposition", "Parallel Agent Deployment",
        "Evidence Verification", "Adversarial Review", "Synthesis", "Finality Proof",
        "Post-Execution Compounding", "IP Extraction", "System Renewal",
        "Asset Build, Test and Operational Release", "Asset Certification and Recertification",
        "Estate Canonicalization and Reconciliation", "Asset Implementation and Pilot Launch",
        "Cross-Asset Regression and Recertification", "Operator Training and Authorization",
    ],
    "Protocol": [
        "Claim Provenance Protocol", "Parallel Independence Protocol",
        "Agent Communication Protocol", "Disagreement Resolution Protocol",
        "Kill-Switch Protocol", "Rollback Protocol", "External Review Protocol",
        "Knowledge Lifecycle Protocol", "Threshold and Evidence Protocol",
        "Asset Dependency and Interface Protocol", "Canonical Naming and Numbering Protocol",
        "Implementation Readiness Protocol", "Regression Assurance Protocol",
        "Evidence Accumulation Protocol",
    ],
    "Council": [
        "Purpose and Strategy Council", "Intelligence and Evidence Council",
        "Creation and Execution Council", "Assurance and Defence Council",
        "Synthesis and Compounding Council",
    ],
    "Layer": [
        "Purpose, Values and Stewardship", "Portfolio, Capital and Resource Allocation",
        "Intent, Requirements and Decision Architecture",
        "Semantic, Knowledge and Ontology Architecture", "Data and Evidence Architecture",
        "Parallel Intelligence and Agent Architecture",
        "Strategy, Scenario and Causal Intelligence", "Product, Service and Customer Architecture",
        "Execution, Programme and Experimentation Architecture",
        "Technology, Infrastructure and Interoperability",
        "Security, Privacy, Safety and Integrity",
        "Risk, Legal, Compliance and Financial Control",
        "Reliability, Resilience and Incident Management",
        "People, Culture, Adoption and Communication",
        "Learning, Memory, IP and Benefits Realization",
        "Scale, Sustainability, Succession and Decommissioning",
    ],
    "Blueprint": [
        "Sovereign Mission Blueprint™", "Parallel Intelligence Deployment Blueprint™",
        "Evidence and Data Sovereignty Blueprint™", "Assurance and Defence Blueprint™",
        "Release and Recovery Blueprint™", "Institutional Learning and IP Blueprint™",
        "Scale and Commercialization Blueprint™", "Succession and Responsible Exit Blueprint™",
        "Asset Industrialization Blueprint™", "Calibre Certification Blueprint™",
    ],
    "Playbook": [
        "Mission Intake and Prioritization Playbook™",
        "Parallel Research and Evidence Playbook™", "Parallel Agent Deployment Playbook™",
        "Decision and Synthesis Playbook™", "Adversarial Assurance Playbook™",
        "Release, Rollback and Incident Playbook™", "Learning and Compounding Playbook™",
        "IP and Commercial Defensibility Playbook™", "Scale and Automation Playbook™",
        "Knowledge Hygiene and Renewal Playbook™",
        "Business Continuity and Succession Playbook™",
        "Responsible Decommissioning Playbook™", "Asset Validation Playbook™",
        "1,000-Calibre Review Playbook™",
    ],
    "Strategy": [
        "Infinite Compounding Strategy™", "Parallel Intelligence Strategy™",
        "Additive Preservation Strategy™", "Proof-Gated Scaling Strategy™",
        "Adaptive Exhaustiveness Strategy™", "Portfolio Sovereignty Strategy™",
        "Trust and Integrity Strategy™", "Commercial Defensibility Strategy™",
        "Human Adoption and Sovereignty Strategy™", "Resilience and Anti-Fragility Strategy™",
        "Succession and Legacy Strategy™", "Responsible Retirement Strategy™",
        "Evidence-to-Scale Strategy™", "Estate Simplification Strategy™",
    ],
    "Assurance System": [
        "Validation Maturity Ladder", "Execution Intensity Matrix",
        "Exhaustiveness Level System", "Lifecycle Decision System",
        "1,000-Point Sovereign Scorecard", "Fatal-Flaw Gate System", "Proof Envelope",
        "Governance Constitution", "Loop Immunity System", "Anti-Complexity System",
        "Zero-Base Review System", "Exhaustiveness Coverage Matrix",
        "Exhaustiveness Release Gate", "Master Artifact Suite", "Validation Roadmap",
        "Master Lifecycle", "Sovereign Asset Assurance Card", "Universal Minimum Test Pack",
        "Asset Calibre Certification System", "Estate Dependency Graph",
    ],
    "Brand Candidate": [
        "LOOP ENGINEERING ∞ + × PARALLEL AGENTS™",
        "Sovereign Compounding Execution and Intelligence Estate™", "LE∞+×PA™",
    ],
}

PREFIXES = {
    "DNA": "DNA", "OS": "OS", "Engine": "ENG", "Framework": "FW",
    "SOP": "SOP", "Protocol": "PRO", "Council": "COU", "Layer": "LAY",
    "Blueprint": "BLU", "Playbook": "PLY", "Strategy": "STR",
    "Assurance System": "ASS", "Brand Candidate": "BRD",
}

OWNER_ROLES = {
    "DNA": "Architecture Steward", "OS": "System Owner", "Engine": "Engine Steward",
    "Framework": "Framework Steward", "SOP": "Process Owner",
    "Protocol": "Governance Owner", "Council": "Council Chair",
    "Layer": "Layer Authority", "Blueprint": "Blueprint Steward",
    "Playbook": "Playbook Owner", "Strategy": "Strategy Owner",
    "Assurance System": "Assurance Owner", "Brand Candidate": "IP Steward",
}

CORE_OS_NUMBERS = {1, 2, 3, 5, 9, 10, 11, 12, 14, 22, 56, 57}
EXPECTED_COUNTS = {family: len(names) for family, names in FAMILIES.items()}
